
// Generated by Cadence Genus(TM) Synthesis Solution 16.24-s065_1
// Generated on: Mar  4 2022 04:32:07 EST (Mar  4 2022 09:32:07 UTC)

// Verification Directory fv/ULA_com_registrador 

module ULA_com_registrador(clk, rst, A, sel, S);
  input clk, rst;
  input [31:0] A;
  input [1:0] sel;
  output [31:0] S;
  wire clk, rst;
  wire [31:0] A;
  wire [1:0] sel;
  wire [31:0] S;
  wire [31:0] S_ULA;
  wire ULA1_n_3846, ULA1_n_3847, ULA1_n_3851, ULA1_n_3852, ULA1_n_3853,
       ULA1_n_3856, ULA1_n_3859, ULA1_n_3860;
  wire ULA1_n_3861, ULA1_n_3865, ULA1_n_3868, ULA1_n_3869, ULA1_n_3870,
       ULA1_n_3873, ULA1_n_3877, ULA1_n_3878;
  wire ULA1_n_3879, ULA1_n_3880, ULA1_n_3885, ULA1_n_3886, ULA1_n_3887,
       ULA1_n_3888, ULA1_n_3893, ULA1_n_3894;
  wire ULA1_n_3895, ULA1_n_3896, ULA1_n_3900, ULA1_n_3901, ULA1_n_3902,
       ULA1_n_3903, ULA1_n_3904, ULA1_n_3909;
  wire ULA1_n_3910, ULA1_n_3911, ULA1_n_3912, ULA1_n_3917, ULA1_n_3918,
       ULA1_n_3919, ULA1_n_3920, ULA1_n_3925;
  wire ULA1_n_3926, ULA1_n_3927, ULA1_n_3928, ULA1_n_3933, ULA1_n_3934,
       ULA1_n_3935, ULA1_n_3936, ULA1_n_3940;
  wire ULA1_n_3941, ULA1_n_3942, ULA1_n_3943, ULA1_n_3944, ULA1_n_3949,
       ULA1_n_3950, ULA1_n_3951, ULA1_n_3952;
  wire ULA1_n_3956, ULA1_n_3957, ULA1_n_3959, ULA1_n_3963, ULA1_n_3964,
       ULA1_n_3968, ULA1_n_3969, ULA1_n_3970;
  wire ULA1_n_3971, ULA1_n_3976, ULA1_n_3977, ULA1_n_3978, ULA1_n_3979,
       ULA1_n_3983, ULA1_n_3984, ULA1_n_3985;
  wire ULA1_n_3986, ULA1_n_3987, ULA1_n_3992, ULA1_n_3993, ULA1_n_3994,
       ULA1_n_3995, ULA1_n_4000, ULA1_n_4001;
  wire ULA1_n_4002, ULA1_n_4003, ULA1_n_4007, ULA1_n_4008, ULA1_n_4009,
       ULA1_n_4010, ULA1_n_4011, ULA1_n_4016;
  wire ULA1_n_4017, ULA1_n_4018, ULA1_n_4019, ULA1_n_4024, ULA1_n_4025,
       ULA1_n_4026, ULA1_n_4027, ULA1_n_4032;
  wire ULA1_n_4033, ULA1_n_4034, ULA1_n_4035, ULA1_n_4037, ULA1_n_4041,
       ULA1_n_4042, ULA1_n_4043, ULA1_n_4044;
  wire ULA1_n_4049, ULA1_n_4050, ULA1_n_4051, ULA1_n_4052, ULA1_n_4057,
       ULA1_n_4058, ULA1_n_4059, ULA1_n_4060;
  wire ULA1_n_4065, ULA1_n_4066, ULA1_n_4067, ULA1_n_4068, ULA1_n_4073,
       ULA1_n_4074, ULA1_n_4075, ULA1_n_4076;
  wire ULA1_n_4081, ULA1_n_4082, ULA1_n_4083, ULA1_n_4084, ULA1_n_4087,
       ULA1_n_4088, ULA1_n_4089, ULA1_n_4090;
  wire ULA1_n_4095, ULA1_n_4096, ULA1_n_4097, ULA1_n_4100, ULA1_n_4102,
       ULA1_n_4104, ULA1_n_4106, ULA1_n_4108;
  wire ULA1_n_4110, ULA1_n_4112, ULA1_n_4114, ULA1_n_4116, ULA1_n_4118,
       ULA1_n_4120, ULA1_n_4122, ULA1_n_4124;
  wire ULA1_n_4126, ULA1_n_4127, ULA1_n_4129, ULA1_n_4131, ULA1_n_4133,
       ULA1_n_4135, ULA1_n_4137, ULA1_n_4139;
  wire ULA1_n_4141, ULA1_n_4143, ULA1_n_4145, ULA1_n_4147, ULA1_n_4148,
       ULA1_n_4150, ULA1_n_4151, ULA1_n_4153;
  wire ULA1_n_4154, ULA1_n_4155, ULA1_n_4157, ULA1_n_4159, ULA1_n_4160,
       ULA1_n_4161, ULA1_n_4162, ULA1_n_4163;
  wire ULA1_n_4165, ULA1_n_4167, ULA1_n_4169, ULA1_n_4171, ULA1_n_4173,
       ULA1_n_4175, ULA1_n_4177, ULA1_n_4179;
  wire ULA1_n_4181, ULA1_n_4183, ULA1_n_4184, ULA1_n_4185, ULA1_n_4186,
       ULA1_n_4188, ULA1_n_4189, ULA1_n_4191;
  wire ULA1_n_4192, ULA1_n_4194, ULA1_n_4195, ULA1_n_4196, ULA1_n_4197,
       ULA1_n_4198, ULA1_n_4200, ULA1_n_4201;
  wire ULA1_n_4203, ULA1_n_4204, ULA1_n_4205, ULA1_n_4206, ULA1_n_4208,
       ULA1_n_4209, ULA1_n_4211, ULA1_n_4213;
  wire ULA1_n_4215, ULA1_n_4216, ULA1_n_4218, ULA1_n_4220, ULA1_n_4222,
       ULA1_n_4223, ULA1_n_4225, ULA1_n_4227;
  wire ULA1_n_4229, ULA1_n_4231, ULA1_n_4236, ULA1_n_4237, ULA1_n_4252,
       ULA1_n_4267, ULA1_n_4268, ULA1_n_4269;
  wire ULA1_n_4270, ULA1_n_4271, ULA1_n_4272, ULA1_n_4273, ULA1_n_4274,
       ULA1_n_4275, ULA1_n_4276, ULA1_n_4277;
  wire ULA1_n_4278, ULA1_n_4279, ULA1_n_4280, ULA1_n_4281, ULA1_n_4282,
       ULA1_n_4283, ULA1_n_4284, ULA1_n_4285;
  wire ULA1_n_4286, ULA1_n_4287, ULA1_n_4288, ULA1_n_4289, ULA1_n_4290,
       ULA1_n_4291, ULA1_n_4293, ULA1_n_4294;
  wire ULA1_n_4295, ULA1_n_4296, ULA1_n_4297, ULA1_n_4298, ULA1_n_4299,
       ULA1_n_4300, ULA1_n_4301, ULA1_n_4302;
  wire ULA1_n_4304, ULA1_n_4305, ULA1_n_4306, ULA1_n_4307, ULA1_n_4308,
       ULA1_n_4309, ULA1_n_4310, ULA1_n_4311;
  wire ULA1_n_4321, ULA1_n_4323, ULA1_n_4336, ULA1_n_4338, ULA1_n_4340,
       ULA1_n_4342, ULA1_n_4345, ULA1_n_4347;
  wire ULA1_n_4349, ULA1_n_4353, ULA1_n_4356, ULA1_n_4359, ULA1_n_4361,
       ULA1_n_4363, ULA1_n_4365, ULA1_n_4384;
  wire ULA1_n_4387, ULA1_n_4390, ULA1_n_4392, ULA1_n_4394, ULA1_n_4396,
       ULA1_n_4398, ULA1_n_4400, ULA1_n_4402;
  wire ULA1_n_4404, ULA1_n_4406, ULA1_n_4408, ULA1_n_4411, ULA1_n_4413,
       ULA1_n_4415, ULA1_n_4417, ULA1_n_4419;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_9,
       n_31, n_32;
  INVERT_A g3(.A (rst), .Z (n_32));
  DFFR_H \registrador1_q_reg[12] (.RN (n_32), .CLK (clk), .D
       (S_ULA[12]), .Q (S[12]), .QBAR (ULA1_n_4342));
  DFFR_H \registrador1_q_reg[1] (.RN (n_32), .CLK (clk), .D (S_ULA[1]),
       .Q (S[1]), .QBAR (ULA1_n_4353));
  DFFR_H \registrador1_q_reg[2] (.RN (n_32), .CLK (clk), .D (S_ULA[2]),
       .Q (S[2]), .QBAR (ULA1_n_4402));
  DFFR_H \registrador1_q_reg[3] (.RN (n_32), .CLK (clk), .D (S_ULA[3]),
       .Q (S[3]), .QBAR (ULA1_n_4356));
  DFFR_H \registrador1_q_reg[4] (.RN (n_32), .CLK (clk), .D (S_ULA[4]),
       .Q (S[4]), .QBAR (ULA1_n_4400));
  DFFR_H \registrador1_q_reg[27] (.RN (n_32), .CLK (clk), .D
       (S_ULA[27]), .Q (S[27]), .QBAR (ULA1_n_4415));
  DFFR_H \registrador1_q_reg[5] (.RN (n_32), .CLK (clk), .D (S_ULA[5]),
       .Q (S[5]), .QBAR (ULA1_n_4345));
  DFFR_H \registrador1_q_reg[6] (.RN (n_32), .CLK (clk), .D (S_ULA[6]),
       .Q (S[6]), .QBAR (ULA1_n_4411));
  DFFR_H \registrador1_q_reg[7] (.RN (n_32), .CLK (clk), .D (S_ULA[7]),
       .Q (S[7]), .QBAR (ULA1_n_4396));
  DFFR_H \registrador1_q_reg[23] (.RN (n_32), .CLK (clk), .D
       (S_ULA[23]), .Q (S[23]), .QBAR (ULA1_n_4394));
  DFFR_H \registrador1_q_reg[8] (.RN (n_32), .CLK (clk), .D (S_ULA[8]),
       .Q (S[8]), .QBAR (ULA1_n_4413));
  DFFR_H \registrador1_q_reg[9] (.RN (n_32), .CLK (clk), .D (S_ULA[9]),
       .Q (S[9]), .QBAR (n_9));
  DFFR_H \registrador1_q_reg[10] (.RN (n_32), .CLK (clk), .D
       (S_ULA[10]), .Q (S[10]), .QBAR (ULA1_n_4417));
  DFFR_H \registrador1_q_reg[11] (.RN (n_32), .CLK (clk), .D
       (S_ULA[11]), .Q (S[11]), .QBAR (ULA1_n_4349));
  DFFR_E \registrador1_q_reg[0] (.RN (n_32), .CLK (clk), .D (S_ULA[0]),
       .Q (S[0]), .QBAR (n_0));
  DFFR_E \registrador1_q_reg[31] (.RN (n_32), .CLK (clk), .D
       (S_ULA[31]), .Q (S[31]), .QBAR (n_31));
  DFFR_H \registrador1_q_reg[14] (.RN (n_32), .CLK (clk), .D
       (S_ULA[14]), .Q (S[14]), .QBAR (ULA1_n_4408));
  DFFR_H \registrador1_q_reg[15] (.RN (n_32), .CLK (clk), .D
       (S_ULA[15]), .Q (S[15]), .QBAR (ULA1_n_4406));
  DFFR_H \registrador1_q_reg[16] (.RN (n_32), .CLK (clk), .D
       (S_ULA[16]), .Q (S[16]), .QBAR (ULA1_n_4336));
  DFFR_H \registrador1_q_reg[17] (.RN (n_32), .CLK (clk), .D
       (S_ULA[17]), .Q (S[17]), .QBAR (ULA1_n_4404));
  DFFR_H \registrador1_q_reg[18] (.RN (n_32), .CLK (clk), .D
       (S_ULA[18]), .Q (S[18]), .QBAR (ULA1_n_4361));
  DFFR_H \registrador1_q_reg[20] (.RN (n_32), .CLK (clk), .D
       (S_ULA[20]), .Q (S[20]), .QBAR (ULA1_n_4340));
  DFFR_H \registrador1_q_reg[22] (.RN (n_32), .CLK (clk), .D
       (S_ULA[22]), .Q (S[22]), .QBAR (ULA1_n_4390));
  DFFR_H \registrador1_q_reg[24] (.RN (n_32), .CLK (clk), .D
       (S_ULA[24]), .Q (S[24]), .QBAR (ULA1_n_4347));
  DFFR_H \registrador1_q_reg[25] (.RN (n_32), .CLK (clk), .D
       (S_ULA[25]), .Q (S[25]), .QBAR (ULA1_n_4398));
  DFFR_H \registrador1_q_reg[26] (.RN (n_32), .CLK (clk), .D
       (S_ULA[26]), .Q (S[26]), .QBAR (ULA1_n_4392));
  DFFR_H \registrador1_q_reg[28] (.RN (n_32), .CLK (clk), .D
       (S_ULA[28]), .Q (S[28]), .QBAR (ULA1_n_4363));
  DFFR_H \registrador1_q_reg[29] (.RN (n_32), .CLK (clk), .D
       (S_ULA[29]), .Q (S[29]), .QBAR (ULA1_n_4359));
  AO22_C ULA1_g8699__7837(.A1 (ULA1_n_3846), .A2 (ULA1_n_4419), .B1
       (S[30]), .B2 (ULA1_n_4237), .Z (S_ULA[31]));
  AO222_E ULA1_g8700__7557(.A1 (S[29]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3851), .B2 (ULA1_n_4419), .C1 (S[31]), .C2
       (ULA1_n_4252), .Z (S_ULA[30]));
  XOR2_C ULA1_g8701__7654(.A (ULA1_n_4155), .B (ULA1_n_3847), .Z
       (ULA1_n_3846));
  OAI21_C ULA1_g8702__8867(.A1 (ULA1_n_3853), .A2 (S[30]), .B
       (ULA1_n_3852), .Z (ULA1_n_3847));
  AO222_E ULA1_g8703__1377(.A1 (S[28]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3859), .B2 (ULA1_n_4419), .C1 (S[30]), .C2
       (ULA1_n_4252), .Z (S_ULA[29]));
  XOR2_C ULA1_g8704__3717(.A (ULA1_n_4154), .B (ULA1_n_3856), .Z
       (ULA1_n_3851));
  AOI22_C ULA1_g8705__4599(.A1 (ULA1_n_3865), .A2 (ULA1_n_4163), .B1
       (ULA1_n_3860), .B2 (ULA1_n_4338), .Z (ULA1_n_3852));
  MUX21I_D ULA1_g8706__3779(.D0 (ULA1_n_3861), .D1 (A[30]), .SD
       (sel[0]), .Z (ULA1_n_3853));
  AO222_E ULA1_g8707__2007(.A1 (S[27]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3869), .B2 (ULA1_n_4419), .C1 (S[29]), .C2
       (ULA1_n_4252), .Z (S_ULA[28]));
  NOR2_E ULA1_g8708__1237(.A (ULA1_n_3860), .B (ULA1_n_3865), .Z
       (ULA1_n_3856));
  XOR2_C ULA1_g8709__1297(.A (ULA1_n_4106), .B (ULA1_n_3870), .Z
       (ULA1_n_3859));
  NAND2_F ULA1_g8710__2006(.A (ULA1_n_3868), .B (A[30]), .Z
       (ULA1_n_3861));
  NOR2_E ULA1_g8711__2833(.A (ULA1_n_3868), .B (sel[0]), .Z
       (ULA1_n_3860));
  AO222_E ULA1_g8712__7547(.A1 (S[26]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3879), .B2 (ULA1_n_4419), .C1 (S[28]), .C2
       (ULA1_n_4252), .Z (S_ULA[27]));
  AOI21_C ULA1_g8713__7765(.A1 (ULA1_n_3873), .A2 (ULA1_n_4173), .B
       (ULA1_n_4365), .Z (ULA1_n_3865));
  OAI21_C ULA1_g8714__9867(.A1 (ULA1_n_3877), .A2 (ULA1_n_4299), .B
       (ULA1_n_4295), .Z (ULA1_n_3868));
  XOR2_C ULA1_g8715__3377(.A (ULA1_n_4118), .B (ULA1_n_3880), .Z
       (ULA1_n_3869));
  MUX21I_D ULA1_g8716__9719(.D0 (ULA1_n_3878), .D1 (ULA1_n_3877), .SD
       (ULA1_n_4365), .Z (ULA1_n_3870));
  OAI21_C ULA1_g8717__1591(.A1 (ULA1_n_4359), .A2 (A[29]), .B
       (ULA1_n_3878), .Z (ULA1_n_3873));
  AO222_E ULA1_g8718__6789(.A1 (S[25]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3887), .B2 (ULA1_n_4419), .C1 (S[27]), .C2
       (ULA1_n_4252), .Z (S_ULA[26]));
  AOI22_C ULA1_g8719__5927(.A1 (ULA1_n_3885), .A2 (ULA1_n_4279), .B1
       (S[28]), .B2 (A[28]), .Z (ULA1_n_3877));
  OAI21_C ULA1_g8720__2001(.A1 (ULA1_n_3886), .A2 (ULA1_n_4216), .B
       (ULA1_n_4204), .Z (ULA1_n_3878));
  XOR2_C ULA1_g8721__1122(.A (ULA1_n_4120), .B (ULA1_n_3888), .Z
       (ULA1_n_3879));
  MUX21_H ULA1_g8722__2005(.D0 (ULA1_n_3886), .D1 (ULA1_n_3885), .SD
       (ULA1_n_4365), .Z (ULA1_n_3880));
  AO222_E ULA1_g8723__9771(.A1 (S[24]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3895), .B2 (ULA1_n_4419), .C1 (S[26]), .C2
       (ULA1_n_4252), .Z (S_ULA[25]));
  AO22_H ULA1_g8724__3457(.A1 (ULA1_n_3893), .A2 (ULA1_n_4185), .B1
       (S[27]), .B2 (A[27]), .Z (ULA1_n_3885));
  OA21_I ULA1_g8725__1279(.A1 (ULA1_n_3894), .A2 (ULA1_n_4205), .B
       (ULA1_n_4213), .Z (ULA1_n_3886));
  XOR2_C ULA1_g8726__6179(.A (ULA1_n_4126), .B (ULA1_n_3896), .Z
       (ULA1_n_3887));
  MUX21_H ULA1_g8727__7837(.D0 (ULA1_n_3894), .D1 (ULA1_n_3893), .SD
       (ULA1_n_4365), .Z (ULA1_n_3888));
  AO222_E ULA1_g8728__7557(.A1 (S[23]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3903), .B2 (ULA1_n_4419), .C1 (S[25]), .C2
       (ULA1_n_4252), .Z (S_ULA[24]));
  OAI21_C ULA1_g8729__7654(.A1 (ULA1_n_3900), .A2 (ULA1_n_4275), .B
       (ULA1_n_4276), .Z (ULA1_n_3893));
  OA21_I ULA1_g8730__8867(.A1 (ULA1_n_3901), .A2 (ULA1_n_4225), .B
       (ULA1_n_4206), .Z (ULA1_n_3894));
  XOR2_C ULA1_g8731__1377(.A (ULA1_n_4127), .B (ULA1_n_3904), .Z
       (ULA1_n_3895));
  MUX21I_D ULA1_g8732__3717(.D0 (ULA1_n_3902), .D1 (ULA1_n_3900), .SD
       (ULA1_n_4365), .Z (ULA1_n_3896));
  AO222_E ULA1_g8733__4599(.A1 (S[22]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3911), .B2 (ULA1_n_4419), .C1 (S[24]), .C2
       (ULA1_n_4252), .Z (S_ULA[23]));
  INVERT_F ULA1_g8734(.A (ULA1_n_3902), .Z (ULA1_n_3901));
  AOI22_C ULA1_g8735__3779(.A1 (ULA1_n_3910), .A2 (ULA1_n_4281), .B1
       (S[25]), .B2 (A[25]), .Z (ULA1_n_3900));
  OAI21_C ULA1_g8736__2007(.A1 (ULA1_n_3909), .A2 (ULA1_n_4218), .B
       (ULA1_n_4208), .Z (ULA1_n_3902));
  XOR2_C ULA1_g8737__1237(.A (ULA1_n_4157), .B (ULA1_n_3912), .Z
       (ULA1_n_3903));
  MUX21I_D ULA1_g8738__1297(.D0 (ULA1_n_3910), .D1 (ULA1_n_3909), .SD
       (sel[0]), .Z (ULA1_n_3904));
  AO222_E ULA1_g8739__2006(.A1 (S[21]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3919), .B2 (ULA1_n_4419), .C1 (S[23]), .C2
       (ULA1_n_4252), .Z (S_ULA[22]));
  AOI22_C ULA1_g8740__2833(.A1 (ULA1_n_3918), .A2 (ULA1_n_4181), .B1
       (ULA1_n_4347), .B2 (A[24]), .Z (ULA1_n_3909));
  OAI21_C ULA1_g8741__7547(.A1 (ULA1_n_3917), .A2 (ULA1_n_4289), .B
       (ULA1_n_4308), .Z (ULA1_n_3910));
  XOR2_C ULA1_g8742__7765(.A (ULA1_n_4133), .B (ULA1_n_3920), .Z
       (ULA1_n_3911));
  MUX21I_D ULA1_g8743__9867(.D0 (ULA1_n_3918), .D1 (ULA1_n_3917), .SD
       (ULA1_n_4365), .Z (ULA1_n_3912));
  AO222_E ULA1_g8744__3377(.A1 (S[20]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3927), .B2 (ULA1_n_4419), .C1 (S[22]), .C2
       (ULA1_n_4252), .Z (S_ULA[21]));
  AOI22_C ULA1_g8745__9719(.A1 (ULA1_n_3926), .A2 (ULA1_n_4280), .B1
       (S[23]), .B2 (A[23]), .Z (ULA1_n_3917));
  OAI21_C ULA1_g8746__1591(.A1 (ULA1_n_3925), .A2 (ULA1_n_4203), .B
       (ULA1_n_4220), .Z (ULA1_n_3918));
  XOR2_C ULA1_g8747__6789(.A (ULA1_n_4137), .B (ULA1_n_3928), .Z
       (ULA1_n_3919));
  MUX21I_D ULA1_g8748__5927(.D0 (ULA1_n_3926), .D1 (ULA1_n_3925), .SD
       (sel[0]), .Z (ULA1_n_3920));
  AO222_E ULA1_g8749__2001(.A1 (S[19]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3935), .B2 (ULA1_n_4419), .C1 (S[21]), .C2
       (ULA1_n_4252), .Z (S_ULA[20]));
  AOI22_C ULA1_g8750__1122(.A1 (ULA1_n_3933), .A2 (ULA1_n_4165), .B1
       (ULA1_n_4390), .B2 (A[22]), .Z (ULA1_n_3925));
  OAI21_C ULA1_g8751__2005(.A1 (ULA1_n_3934), .A2 (ULA1_n_4294), .B
       (ULA1_n_4300), .Z (ULA1_n_3926));
  XOR2_C ULA1_g8752__9771(.A (ULA1_n_4141), .B (ULA1_n_3936), .Z
       (ULA1_n_3927));
  MUX21_H ULA1_g8753__3457(.D0 (ULA1_n_3934), .D1 (ULA1_n_3933), .SD
       (sel[0]), .Z (ULA1_n_3928));
  AO222_E ULA1_g8754__1279(.A1 (S[18]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3943), .B2 (ULA1_n_4419), .C1 (S[20]), .C2
       (ULA1_n_4252), .Z (S_ULA[19]));
  OAI22_B ULA1_g8755__6179(.A1 (ULA1_n_3940), .A2 (ULA1_n_4184), .B1
       (S[21]), .B2 (ULA1_n_4321), .Z (ULA1_n_3933));
  OA21_I ULA1_g8756__7837(.A1 (ULA1_n_3941), .A2 (ULA1_n_4290), .B
       (ULA1_n_4311), .Z (ULA1_n_3934));
  XOR2_C ULA1_g8757__7557(.A (ULA1_n_4145), .B (ULA1_n_3944), .Z
       (ULA1_n_3935));
  MUX21I_D ULA1_g8758__7654(.D0 (ULA1_n_3942), .D1 (ULA1_n_3940), .SD
       (sel[0]), .Z (ULA1_n_3936));
  AO222_E ULA1_g8759__8867(.A1 (S[17]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3951), .B2 (ULA1_n_4419), .C1 (S[19]), .C2
       (ULA1_n_4252), .Z (S_ULA[18]));
  INVERT_F ULA1_g8760(.A (ULA1_n_3942), .Z (ULA1_n_3941));
  AOI22_C ULA1_g8761__1377(.A1 (ULA1_n_3950), .A2 (ULA1_n_4177), .B1
       (ULA1_n_4340), .B2 (A[20]), .Z (ULA1_n_3940));
  OAI21_C ULA1_g8762__3717(.A1 (ULA1_n_3949), .A2 (ULA1_n_4200), .B
       (ULA1_n_4306), .Z (ULA1_n_3942));
  XOR2_C ULA1_g8763__4599(.A (ULA1_n_4147), .B (ULA1_n_3952), .Z
       (ULA1_n_3943));
  MUX21_H ULA1_g8764__3779(.D0 (ULA1_n_3949), .D1 (ULA1_n_3950), .SD
       (sel[0]), .Z (ULA1_n_3944));
  AO222_E ULA1_g8765__2007(.A1 (S[16]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3963), .B2 (ULA1_n_4419), .C1 (S[18]), .C2
       (ULA1_n_4252), .Z (S_ULA[17]));
  OA21_I ULA1_g8766__1237(.A1 (ULA1_n_3956), .A2 (ULA1_n_4291), .B
       (ULA1_n_4298), .Z (ULA1_n_3949));
  OAI22_B ULA1_g8767__1297(.A1 (ULA1_n_3959), .A2 (ULA1_n_4159), .B1
       (S[19]), .B2 (ULA1_n_4384), .Z (ULA1_n_3950));
  XOR2_C ULA1_g8768__2006(.A (ULA1_n_4150), .B (ULA1_n_3964), .Z
       (ULA1_n_3951));
  MUX21I_D ULA1_g8769__2833(.D0 (ULA1_n_3957), .D1 (ULA1_n_3956), .SD
       (ULA1_n_4365), .Z (ULA1_n_3952));
  AO222_E ULA1_g8770__7547(.A1 (S[15]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3970), .B2 (ULA1_n_4419), .C1 (S[17]), .C2
       (ULA1_n_4252), .Z (S_ULA[16]));
  OAI21_C ULA1_g8771__7765(.A1 (ULA1_n_3969), .A2 (ULA1_n_4159), .B
       (ULA1_n_4161), .Z (ULA1_n_3957));
  AOI22_C ULA1_g8772__9867(.A1 (ULA1_n_3968), .A2 (ULA1_n_4273), .B1
       (S[18]), .B2 (A[18]), .Z (ULA1_n_3956));
  AO22_F ULA1_g8773__3377(.A1 (ULA1_n_3969), .A2 (ULA1_n_4161), .B1
       (S[19]), .B2 (ULA1_n_4384), .Z (ULA1_n_3959));
  XOR2_C ULA1_g8774__9719(.A (ULA1_n_4151), .B (ULA1_n_3971), .Z
       (ULA1_n_3963));
  MUX21_H ULA1_g8775__1591(.D0 (ULA1_n_3969), .D1 (ULA1_n_3968), .SD
       (ULA1_n_4365), .Z (ULA1_n_3964));
  AO222_E ULA1_g8776__6789(.A1 (S[14]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3978), .B2 (ULA1_n_4419), .C1 (S[16]), .C2
       (ULA1_n_4252), .Z (S_ULA[15]));
  AO22_H ULA1_g8777__5927(.A1 (ULA1_n_3976), .A2 (ULA1_n_4271), .B1
       (S[17]), .B2 (A[17]), .Z (ULA1_n_3968));
  OA21_I ULA1_g8778__2001(.A1 (ULA1_n_3977), .A2 (ULA1_n_4222), .B
       (ULA1_n_4227), .Z (ULA1_n_3969));
  XOR2_C ULA1_g8779__1122(.A (ULA1_n_4153), .B (ULA1_n_3979), .Z
       (ULA1_n_3970));
  MUX21_H ULA1_g8780__2005(.D0 (ULA1_n_3977), .D1 (ULA1_n_3976), .SD
       (ULA1_n_4365), .Z (ULA1_n_3971));
  AO222_E ULA1_g8781__9771(.A1 (S[13]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3986), .B2 (ULA1_n_4419), .C1 (S[15]), .C2
       (ULA1_n_4252), .Z (S_ULA[14]));
  OAI21_C ULA1_g8782__3457(.A1 (ULA1_n_3983), .A2 (ULA1_n_4270), .B
       (ULA1_n_4272), .Z (ULA1_n_3976));
  OA21_I ULA1_g8783__1279(.A1 (ULA1_n_3984), .A2 (ULA1_n_4223), .B
       (ULA1_n_4198), .Z (ULA1_n_3977));
  XOR2_C ULA1_g8784__6179(.A (ULA1_n_4129), .B (ULA1_n_3987), .Z
       (ULA1_n_3978));
  MUX21I_D ULA1_g8785__7837(.D0 (ULA1_n_3985), .D1 (ULA1_n_3983), .SD
       (ULA1_n_4365), .Z (ULA1_n_3979));
  AO222_E ULA1_g8786__7557(.A1 (S[12]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_3994), .B2 (ULA1_n_4419), .C1 (S[14]), .C2
       (ULA1_n_4252), .Z (S_ULA[13]));
  INVERT_F ULA1_g8787(.A (ULA1_n_3985), .Z (ULA1_n_3984));
  AOI22_C ULA1_g8788__7654(.A1 (ULA1_n_3993), .A2 (ULA1_n_4268), .B1
       (S[15]), .B2 (A[15]), .Z (ULA1_n_3983));
  OAI21_C ULA1_g8789__8867(.A1 (ULA1_n_3992), .A2 (ULA1_n_4231), .B
       (ULA1_n_4196), .Z (ULA1_n_3985));
  XOR2_C ULA1_g8790__1377(.A (ULA1_n_4124), .B (ULA1_n_3995), .Z
       (ULA1_n_3986));
  MUX21I_D ULA1_g8791__3717(.D0 (ULA1_n_3993), .D1 (ULA1_n_3992), .SD
       (sel[0]), .Z (ULA1_n_3987));
  AO222_E ULA1_g8792__4599(.A1 (S[11]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4002), .B2 (ULA1_n_4419), .C1 (S[13]), .C2
       (ULA1_n_4252), .Z (S_ULA[12]));
  AOI22_C ULA1_g8793__3779(.A1 (ULA1_n_4000), .A2 (ULA1_n_4179), .B1
       (ULA1_n_4408), .B2 (A[14]), .Z (ULA1_n_3992));
  OAI21_C ULA1_g8794__2007(.A1 (ULA1_n_4001), .A2 (ULA1_n_4285), .B
       (ULA1_n_4301), .Z (ULA1_n_3993));
  XOR2_C ULA1_g8795__1237(.A (ULA1_n_4102), .B (ULA1_n_4003), .Z
       (ULA1_n_3994));
  MUX21_H ULA1_g8796__1297(.D0 (ULA1_n_4001), .D1 (ULA1_n_4000), .SD
       (sel[0]), .Z (ULA1_n_3995));
  AO222_E ULA1_g8797__2006(.A1 (S[10]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4010), .B2 (ULA1_n_4419), .C1 (S[12]), .C2
       (ULA1_n_4252), .Z (S_ULA[11]));
  OAI22_B ULA1_g8798__2833(.A1 (ULA1_n_4007), .A2 (ULA1_n_4183), .B1
       (S[13]), .B2 (ULA1_n_4323), .Z (ULA1_n_4000));
  OA21_I ULA1_g8799__7547(.A1 (ULA1_n_4008), .A2 (ULA1_n_4296), .B
       (ULA1_n_4302), .Z (ULA1_n_4001));
  XOR2_C ULA1_g8800__7765(.A (ULA1_n_4148), .B (ULA1_n_4011), .Z
       (ULA1_n_4002));
  MUX21I_D ULA1_g8801__9867(.D0 (ULA1_n_4009), .D1 (ULA1_n_4007), .SD
       (sel[0]), .Z (ULA1_n_4003));
  AO222_E ULA1_g8802__3377(.A1 (S[9]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4018), .B2 (ULA1_n_4419), .C1 (S[11]), .C2
       (ULA1_n_4252), .Z (S_ULA[10]));
  INVERT_F ULA1_g8803(.A (ULA1_n_4009), .Z (ULA1_n_4008));
  AOI22_C ULA1_g8804__9719(.A1 (ULA1_n_4017), .A2 (ULA1_n_4167), .B1
       (ULA1_n_4342), .B2 (A[12]), .Z (ULA1_n_4007));
  OAI21_C ULA1_g8805__1591(.A1 (ULA1_n_4016), .A2 (ULA1_n_4287), .B
       (ULA1_n_4283), .Z (ULA1_n_4009));
  XOR2_C ULA1_g8806__6789(.A (ULA1_n_4143), .B (ULA1_n_4019), .Z
       (ULA1_n_4010));
  MUX21I_D ULA1_g8807__5927(.D0 (ULA1_n_4017), .D1 (ULA1_n_4016), .SD
       (ULA1_n_4365), .Z (ULA1_n_4011));
  AO222_E ULA1_g8808__2001(.A1 (S[8]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4026), .B2 (ULA1_n_4419), .C1 (S[10]), .C2
       (ULA1_n_4252), .Z (S_ULA[9]));
  AOI22_C ULA1_g8809__1122(.A1 (ULA1_n_4025), .A2 (ULA1_n_4267), .B1
       (S[11]), .B2 (A[11]), .Z (ULA1_n_4016));
  OAI21_C ULA1_g8810__2005(.A1 (ULA1_n_4024), .A2 (ULA1_n_4195), .B
       (ULA1_n_4209), .Z (ULA1_n_4017));
  XOR2_C ULA1_g8811__9771(.A (ULA1_n_4139), .B (ULA1_n_4027), .Z
       (ULA1_n_4018));
  MUX21I_D ULA1_g8812__3457(.D0 (ULA1_n_4025), .D1 (ULA1_n_4024), .SD
       (sel[0]), .Z (ULA1_n_4019));
  AO222_E ULA1_g8813__1279(.A1 (S[7]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4034), .B2 (ULA1_n_4419), .C1 (S[9]), .C2 (ULA1_n_4252),
       .Z (S_ULA[8]));
  AOI22_C ULA1_g8814__6179(.A1 (ULA1_n_4032), .A2 (ULA1_n_4186), .B1
       (ULA1_n_4417), .B2 (A[10]), .Z (ULA1_n_4024));
  OAI21_C ULA1_g8815__7837(.A1 (ULA1_n_4033), .A2 (ULA1_n_4286), .B
       (ULA1_n_4304), .Z (ULA1_n_4025));
  XOR2_C ULA1_g8816__7557(.A (ULA1_n_4104), .B (ULA1_n_4035), .Z
       (ULA1_n_4026));
  MUX21_H ULA1_g8817__7654(.D0 (ULA1_n_4033), .D1 (ULA1_n_4032), .SD
       (sel[0]), .Z (ULA1_n_4027));
  AO222_E ULA1_g8818__8867(.A1 (S[6]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4043), .B2 (ULA1_n_4419), .C1 (S[8]), .C2 (ULA1_n_4252),
       .Z (S_ULA[7]));
  OAI21_C ULA1_g8819__1377(.A1 (S[9]), .A2 (ULA1_n_4387), .B
       (ULA1_n_4037), .Z (ULA1_n_4032));
  OA21_I ULA1_g8820__3717(.A1 (ULA1_n_4041), .A2 (ULA1_n_4309), .B
       (ULA1_n_4310), .Z (ULA1_n_4033));
  XOR2_C ULA1_g8821__4599(.A (ULA1_n_4135), .B (ULA1_n_4044), .Z
       (ULA1_n_4034));
  MUX21I_D ULA1_g8822__3779(.D0 (ULA1_n_4042), .D1 (ULA1_n_4041), .SD
       (ULA1_n_4365), .Z (ULA1_n_4035));
  OAI21_C ULA1_g8823__2007(.A1 (n_9), .A2 (A[9]), .B (ULA1_n_4042), .Z
       (ULA1_n_4037));
  AO222_E ULA1_g8824__1237(.A1 (S[5]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4051), .B2 (ULA1_n_4419), .C1 (S[7]), .C2 (ULA1_n_4252),
       .Z (S_ULA[6]));
  AOI22_C ULA1_g8825__1297(.A1 (ULA1_n_4050), .A2 (ULA1_n_4269), .B1
       (S[8]), .B2 (A[8]), .Z (ULA1_n_4041));
  OAI21_C ULA1_g8826__2006(.A1 (ULA1_n_4049), .A2 (ULA1_n_4215), .B
       (ULA1_n_4229), .Z (ULA1_n_4042));
  XOR2_C ULA1_g8827__2833(.A (ULA1_n_4100), .B (ULA1_n_4052), .Z
       (ULA1_n_4043));
  MUX21I_D ULA1_g8828__7547(.D0 (ULA1_n_4049), .D1 (ULA1_n_4050), .SD
       (ULA1_n_4365), .Z (ULA1_n_4044));
  AO222_E ULA1_g8829__7765(.A1 (S[4]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4059), .B2 (ULA1_n_4419), .C1 (S[6]), .C2 (ULA1_n_4252),
       .Z (S_ULA[5]));
  AOI22_C ULA1_g8830__9867(.A1 (ULA1_n_4058), .A2 (ULA1_n_4171), .B1
       (ULA1_n_4396), .B2 (A[7]), .Z (ULA1_n_4049));
  OAI21_C ULA1_g8831__3377(.A1 (ULA1_n_4057), .A2 (ULA1_n_4284), .B
       (ULA1_n_4307), .Z (ULA1_n_4050));
  XOR2_C ULA1_g8832__9719(.A (ULA1_n_4122), .B (ULA1_n_4060), .Z
       (ULA1_n_4051));
  MUX21I_D ULA1_g8833__1591(.D0 (ULA1_n_4058), .D1 (ULA1_n_4057), .SD
       (ULA1_n_4365), .Z (ULA1_n_4052));
  AO222_E ULA1_g8834__6789(.A1 (S[3]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4067), .B2 (ULA1_n_4419), .C1 (S[5]), .C2 (ULA1_n_4252),
       .Z (S_ULA[4]));
  AOI22_C ULA1_g8835__5927(.A1 (ULA1_n_4066), .A2 (ULA1_n_4277), .B1
       (S[6]), .B2 (A[6]), .Z (ULA1_n_4057));
  OAI21_C ULA1_g8836__2001(.A1 (ULA1_n_4065), .A2 (ULA1_n_4197), .B
       (ULA1_n_4201), .Z (ULA1_n_4058));
  XOR2_C ULA1_g8837__1122(.A (ULA1_n_4110), .B (ULA1_n_4068), .Z
       (ULA1_n_4059));
  MUX21I_D ULA1_g8838__2005(.D0 (ULA1_n_4066), .D1 (ULA1_n_4065), .SD
       (sel[0]), .Z (ULA1_n_4060));
  AO222_E ULA1_g8839__9771(.A1 (S[2]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4075), .B2 (ULA1_n_4419), .C1 (S[4]), .C2 (ULA1_n_4252),
       .Z (S_ULA[3]));
  AOI22_C ULA1_g8840__3457(.A1 (ULA1_n_4074), .A2 (ULA1_n_4175), .B1
       (ULA1_n_4345), .B2 (A[5]), .Z (ULA1_n_4065));
  OAI21_C ULA1_g8841__1279(.A1 (ULA1_n_4073), .A2 (ULA1_n_4288), .B
       (ULA1_n_4293), .Z (ULA1_n_4066));
  XOR2_C ULA1_g8842__6179(.A (ULA1_n_4116), .B (ULA1_n_4076), .Z
       (ULA1_n_4067));
  MUX21I_D ULA1_g8843__7837(.D0 (ULA1_n_4074), .D1 (ULA1_n_4073), .SD
       (ULA1_n_4365), .Z (ULA1_n_4068));
  AO222_E ULA1_g8844__7557(.A1 (S[1]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4083), .B2 (ULA1_n_4419), .C1 (S[3]), .C2 (ULA1_n_4252),
       .Z (S_ULA[2]));
  AOI22_C ULA1_g8845__7654(.A1 (ULA1_n_4081), .A2 (ULA1_n_4274), .B1
       (S[4]), .B2 (A[4]), .Z (ULA1_n_4073));
  OAI21_C ULA1_g8846__8867(.A1 (ULA1_n_4082), .A2 (ULA1_n_4194), .B
       (ULA1_n_4211), .Z (ULA1_n_4074));
  XNOR2_C ULA1_g8847__1377(.A (ULA1_n_4108), .B (ULA1_n_4084), .Z
       (ULA1_n_4075));
  MUX21_H ULA1_g8848__3717(.D0 (ULA1_n_4082), .D1 (ULA1_n_4081), .SD
       (ULA1_n_4365), .Z (ULA1_n_4076));
  AO222_E ULA1_g8849__4599(.A1 (S[0]), .A2 (ULA1_n_4237), .B1
       (ULA1_n_4089), .B2 (ULA1_n_4419), .C1 (S[2]), .C2 (ULA1_n_4252),
       .Z (S_ULA[1]));
  AO22_H ULA1_g8850__3779(.A1 (ULA1_n_4088), .A2 (ULA1_n_4278), .B1
       (S[3]), .B2 (A[3]), .Z (ULA1_n_4081));
  OA21_I ULA1_g8851__2007(.A1 (ULA1_n_4087), .A2 (ULA1_n_4188), .B
       (ULA1_n_4189), .Z (ULA1_n_4082));
  XOR2_C ULA1_g8852__1237(.A (ULA1_n_4112), .B (ULA1_n_4090), .Z
       (ULA1_n_4083));
  MUX21I_D ULA1_g8853__1297(.D0 (ULA1_n_4087), .D1 (ULA1_n_4088), .SD
       (ULA1_n_4365), .Z (ULA1_n_4084));
  AOI22_C ULA1_g8854__2006(.A1 (ULA1_n_4096), .A2 (ULA1_n_4169), .B1
       (ULA1_n_4402), .B2 (A[2]), .Z (ULA1_n_4087));
  OAI21_C ULA1_g8855__2833(.A1 (ULA1_n_4095), .A2 (ULA1_n_4297), .B
       (ULA1_n_4305), .Z (ULA1_n_4088));
  XOR2_C ULA1_g8856__7547(.A (ULA1_n_4114), .B (ULA1_n_4097), .Z
       (ULA1_n_4089));
  MUX21I_D ULA1_g8857__7765(.D0 (ULA1_n_4095), .D1 (ULA1_n_4096), .SD
       (sel[0]), .Z (ULA1_n_4090));
  AO22_C ULA1_g8858__9867(.A1 (ULA1_n_4131), .A2 (ULA1_n_4419), .B1
       (S[1]), .B2 (ULA1_n_4252), .Z (S_ULA[0]));
  AOI22_C ULA1_g8859__3377(.A1 (ULA1_n_4236), .A2 (ULA1_n_4282), .B1
       (S[1]), .B2 (A[1]), .Z (ULA1_n_4095));
  OAI21_C ULA1_g8860__9719(.A1 (ULA1_n_4191), .A2 (ULA1_n_4162), .B
       (ULA1_n_4192), .Z (ULA1_n_4096));
  MUX21_H ULA1_g8861__1591(.D0 (ULA1_n_4162), .D1 (ULA1_n_4236), .SD
       (ULA1_n_4365), .Z (ULA1_n_4097));
  XOR2_C ULA1_g8862__6789(.A (A[7]), .B (S[7]), .Z (ULA1_n_4100));
  XOR2_C ULA1_g8863__5927(.A (ULA1_n_4323), .B (S[13]), .Z
       (ULA1_n_4102));
  XOR2_C ULA1_g8864__2001(.A (A[9]), .B (S[9]), .Z (ULA1_n_4104));
  XOR2_C ULA1_g8865__1122(.A (A[29]), .B (S[29]), .Z (ULA1_n_4106));
  XOR2_C ULA1_g8866__2005(.A (A[3]), .B (S[3]), .Z (ULA1_n_4108));
  XOR2_C ULA1_g8867__9771(.A (A[5]), .B (S[5]), .Z (ULA1_n_4110));
  XOR2_C ULA1_g8868__3457(.A (A[2]), .B (S[2]), .Z (ULA1_n_4112));
  XOR2_C ULA1_g8869__1279(.A (A[1]), .B (S[1]), .Z (ULA1_n_4114));
  XOR2_C ULA1_g8870__6179(.A (A[4]), .B (S[4]), .Z (ULA1_n_4116));
  XOR2_C ULA1_g8871__7837(.A (A[28]), .B (S[28]), .Z (ULA1_n_4118));
  XOR2_C ULA1_g8872__7557(.A (A[27]), .B (S[27]), .Z (ULA1_n_4120));
  XNOR2_C ULA1_g8873__7654(.A (A[6]), .B (S[6]), .Z (ULA1_n_4122));
  XNOR2_C ULA1_g8874__8867(.A (A[14]), .B (S[14]), .Z (ULA1_n_4124));
  XOR2_C ULA1_g8875__1377(.A (A[26]), .B (S[26]), .Z (ULA1_n_4126));
  XNOR2_C ULA1_g8876__3717(.A (A[25]), .B (S[25]), .Z (ULA1_n_4127));
  XNOR2_C ULA1_g8877__4599(.A (A[15]), .B (S[15]), .Z (ULA1_n_4129));
  XOR2_C ULA1_g8878__3779(.A (A[0]), .B (S[0]), .Z (ULA1_n_4131));
  XNOR2_C ULA1_g8879__2007(.A (A[23]), .B (S[23]), .Z (ULA1_n_4133));
  XNOR2_C ULA1_g8880__1237(.A (A[8]), .B (S[8]), .Z (ULA1_n_4135));
  XNOR2_C ULA1_g8881__1297(.A (A[22]), .B (S[22]), .Z (ULA1_n_4137));
  XNOR2_C ULA1_g8882__2006(.A (A[10]), .B (S[10]), .Z (ULA1_n_4139));
  XOR2_C ULA1_g8883__2833(.A (ULA1_n_4321), .B (S[21]), .Z
       (ULA1_n_4141));
  XNOR2_C ULA1_g8884__7547(.A (A[11]), .B (S[11]), .Z (ULA1_n_4143));
  XNOR2_C ULA1_g8885__7765(.A (A[20]), .B (S[20]), .Z (ULA1_n_4145));
  XOR2_C ULA1_g8886__9867(.A (A[19]), .B (S[19]), .Z (ULA1_n_4147));
  XOR2_C ULA1_g8887__3377(.A (A[12]), .B (S[12]), .Z (ULA1_n_4148));
  NAND2_F ULA1_g8888__9719(.A (ULA1_n_4161), .B (ULA1_n_4160), .Z
       (ULA1_n_4150));
  XOR2_C ULA1_g8889__1591(.A (A[17]), .B (S[17]), .Z (ULA1_n_4151));
  XOR2_C ULA1_g8890__6789(.A (A[16]), .B (S[16]), .Z (ULA1_n_4153));
  XOR2_C ULA1_g8891__5927(.A (A[30]), .B (S[30]), .Z (ULA1_n_4154));
  XNOR2_C ULA1_g8892__2001(.A (A[31]), .B (S[31]), .Z (ULA1_n_4155));
  XOR2_C ULA1_g8893__1122(.A (A[24]), .B (S[24]), .Z (ULA1_n_4157));
  INVERT_E ULA1_g8894(.A (ULA1_n_4159), .Z (ULA1_n_4160));
  NAND2_F ULA1_g8895__2005(.A (S[30]), .B (ULA1_n_4338), .Z
       (ULA1_n_4163));
  OR2_I ULA1_g8896__9771(.A (ULA1_n_4390), .B (A[22]), .Z
       (ULA1_n_4165));
  OR2_I ULA1_g8897__3457(.A (ULA1_n_4342), .B (A[12]), .Z
       (ULA1_n_4167));
  OR2_I ULA1_g8898__1279(.A (ULA1_n_4402), .B (A[2]), .Z (ULA1_n_4169));
  OR2_I ULA1_g8899__6179(.A (ULA1_n_4396), .B (A[7]), .Z (ULA1_n_4171));
  NAND2_E ULA1_g8900__7837(.A (ULA1_n_4359), .B (A[29]), .Z
       (ULA1_n_4173));
  OR2_I ULA1_g8901__7557(.A (ULA1_n_4345), .B (A[5]), .Z (ULA1_n_4175));
  OR2_I ULA1_g8902__7654(.A (ULA1_n_4340), .B (A[20]), .Z
       (ULA1_n_4177));
  OR2_I ULA1_g8903__8867(.A (ULA1_n_4408), .B (A[14]), .Z
       (ULA1_n_4179));
  OR2_I ULA1_g8904__1377(.A (ULA1_n_4347), .B (A[24]), .Z
       (ULA1_n_4181));
  AND2_F ULA1_g8905__3717(.A (S[13]), .B (ULA1_n_4323), .Z
       (ULA1_n_4183));
  AND2_F ULA1_g8906__4599(.A (S[21]), .B (ULA1_n_4321), .Z
       (ULA1_n_4184));
  OR2_I ULA1_g8907__3779(.A (S[27]), .B (A[27]), .Z (ULA1_n_4185));
  OR2_I ULA1_g8908__2007(.A (ULA1_n_4417), .B (A[10]), .Z
       (ULA1_n_4186));
  NOR2_E ULA1_g8909__1237(.A (ULA1_n_4356), .B (A[3]), .Z
       (ULA1_n_4188));
  NAND2_F ULA1_g8910__1297(.A (ULA1_n_4356), .B (A[3]), .Z
       (ULA1_n_4189));
  NOR2_E ULA1_g8911__2006(.A (ULA1_n_4353), .B (A[1]), .Z
       (ULA1_n_4191));
  NAND2_F ULA1_g8912__2833(.A (ULA1_n_4353), .B (A[1]), .Z
       (ULA1_n_4192));
  NOR2_E ULA1_g8913__7547(.A (ULA1_n_4400), .B (A[4]), .Z
       (ULA1_n_4194));
  NOR2_E ULA1_g8914__7765(.A (ULA1_n_4349), .B (A[11]), .Z
       (ULA1_n_4195));
  NAND2_F ULA1_g8915__9867(.A (ULA1_n_4406), .B (A[15]), .Z
       (ULA1_n_4196));
  NOR2_E ULA1_g8916__3377(.A (ULA1_n_4411), .B (A[6]), .Z
       (ULA1_n_4197));
  NAND2_F ULA1_g8917__9719(.A (ULA1_n_4336), .B (A[16]), .Z
       (ULA1_n_4198));
  NOR2_E ULA1_g8918__1591(.A (S[20]), .B (A[20]), .Z (ULA1_n_4200));
  NAND2_F ULA1_g8919__6789(.A (ULA1_n_4411), .B (A[6]), .Z
       (ULA1_n_4201));
  NOR2_E ULA1_g8920__5927(.A (ULA1_n_4394), .B (A[23]), .Z
       (ULA1_n_4203));
  NAND2_E ULA1_g8921__2001(.A (ULA1_n_4363), .B (A[28]), .Z
       (ULA1_n_4204));
  NOR2_E ULA1_g8922__1122(.A (ULA1_n_4415), .B (A[27]), .Z
       (ULA1_n_4205));
  NAND2_F ULA1_g8923__2005(.A (ULA1_n_4392), .B (A[26]), .Z
       (ULA1_n_4206));
  NAND2_E ULA1_g8924__9771(.A (ULA1_n_4398), .B (A[25]), .Z
       (ULA1_n_4208));
  NAND2_F ULA1_g8925__3457(.A (ULA1_n_4349), .B (A[11]), .Z
       (ULA1_n_4209));
  NAND2_F ULA1_g8926__1279(.A (ULA1_n_4400), .B (A[4]), .Z
       (ULA1_n_4211));
  NAND2_F ULA1_g8927__6179(.A (ULA1_n_4415), .B (A[27]), .Z
       (ULA1_n_4213));
  NOR2_E ULA1_g8928__7837(.A (ULA1_n_4413), .B (A[8]), .Z
       (ULA1_n_4215));
  NOR2_E ULA1_g8929__7557(.A (ULA1_n_4363), .B (A[28]), .Z
       (ULA1_n_4216));
  NOR2_E ULA1_g8930__7654(.A (ULA1_n_4398), .B (A[25]), .Z
       (ULA1_n_4218));
  NAND2_F ULA1_g8931__8867(.A (ULA1_n_4394), .B (A[23]), .Z
       (ULA1_n_4220));
  NOR2_E ULA1_g8932__1377(.A (ULA1_n_4404), .B (A[17]), .Z
       (ULA1_n_4222));
  NOR2_E ULA1_g8933__3717(.A (ULA1_n_4336), .B (A[16]), .Z
       (ULA1_n_4223));
  NOR2_E ULA1_g8934__4599(.A (ULA1_n_4392), .B (A[26]), .Z
       (ULA1_n_4225));
  NAND2_F ULA1_g8935__3779(.A (ULA1_n_4404), .B (A[17]), .Z
       (ULA1_n_4227));
  NAND2_F ULA1_g8936__2007(.A (ULA1_n_4413), .B (A[8]), .Z
       (ULA1_n_4229));
  NOR2_E ULA1_g8937__1237(.A (ULA1_n_4406), .B (A[15]), .Z
       (ULA1_n_4231));
  NOR2_E ULA1_g8938__1297(.A (ULA1_n_4361), .B (A[18]), .Z
       (ULA1_n_4159));
  NAND2_F ULA1_g8939__2006(.A (ULA1_n_4361), .B (A[18]), .Z
       (ULA1_n_4161));
  NOR2_E ULA1_g8940__2833(.A (n_0), .B (A[0]), .Z (ULA1_n_4162));
  OR2_I ULA1_g8941__7547(.A (S[11]), .B (A[11]), .Z (ULA1_n_4267));
  OR2_I ULA1_g8942__7765(.A (S[15]), .B (A[15]), .Z (ULA1_n_4268));
  OR2_I ULA1_g8943__9867(.A (S[8]), .B (A[8]), .Z (ULA1_n_4269));
  NOR2_E ULA1_g8944__3377(.A (S[16]), .B (A[16]), .Z (ULA1_n_4270));
  OR2_I ULA1_g8945__9719(.A (S[17]), .B (A[17]), .Z (ULA1_n_4271));
  NAND2_F ULA1_g8946__1591(.A (S[16]), .B (A[16]), .Z (ULA1_n_4272));
  OR2_I ULA1_g8947__6789(.A (S[18]), .B (A[18]), .Z (ULA1_n_4273));
  OR2_I ULA1_g8948__5927(.A (S[4]), .B (A[4]), .Z (ULA1_n_4274));
  NOR2_E ULA1_g8949__2001(.A (S[26]), .B (A[26]), .Z (ULA1_n_4275));
  NAND2_F ULA1_g8950__1122(.A (S[26]), .B (A[26]), .Z (ULA1_n_4276));
  OR2_I ULA1_g8951__2005(.A (S[6]), .B (A[6]), .Z (ULA1_n_4277));
  OR2_I ULA1_g8952__9771(.A (S[3]), .B (A[3]), .Z (ULA1_n_4278));
  OR2_I ULA1_g8953__3457(.A (S[28]), .B (A[28]), .Z (ULA1_n_4279));
  OR2_I ULA1_g8954__1279(.A (S[23]), .B (A[23]), .Z (ULA1_n_4280));
  OR2_I ULA1_g8955__6179(.A (S[25]), .B (A[25]), .Z (ULA1_n_4281));
  OR2_I ULA1_g8956__7837(.A (S[1]), .B (A[1]), .Z (ULA1_n_4282));
  NAND2_F ULA1_g8957__7557(.A (S[12]), .B (A[12]), .Z (ULA1_n_4283));
  NOR2_E ULA1_g8958__7654(.A (S[7]), .B (A[7]), .Z (ULA1_n_4284));
  NOR2_E ULA1_g8959__8867(.A (S[14]), .B (A[14]), .Z (ULA1_n_4285));
  NOR2_E ULA1_g8960__1377(.A (S[10]), .B (A[10]), .Z (ULA1_n_4286));
  NOR2_E ULA1_g8961__3717(.A (S[12]), .B (A[12]), .Z (ULA1_n_4287));
  NOR2_E ULA1_g8962__4599(.A (S[5]), .B (A[5]), .Z (ULA1_n_4288));
  NOR2_E ULA1_g8963__3779(.A (S[24]), .B (A[24]), .Z (ULA1_n_4289));
  AND2_I ULA1_g8964__2007(.A (S[0]), .B (A[0]), .Z (ULA1_n_4236));
  NOR2_E ULA1_g8965__1237(.A (S[21]), .B (A[21]), .Z (ULA1_n_4290));
  NOR2_E ULA1_g8966__1297(.A (S[19]), .B (A[19]), .Z (ULA1_n_4291));
  NAND2_F ULA1_g8967__2006(.A (S[5]), .B (A[5]), .Z (ULA1_n_4293));
  NOR2_E ULA1_g8968__2833(.A (S[22]), .B (A[22]), .Z (ULA1_n_4294));
  NAND2_F ULA1_g8969__7547(.A (S[29]), .B (A[29]), .Z (ULA1_n_4295));
  NOR2_E ULA1_g8970__7765(.A (S[13]), .B (A[13]), .Z (ULA1_n_4296));
  NOR2_E ULA1_g8971__9867(.A (S[2]), .B (A[2]), .Z (ULA1_n_4297));
  NAND2_F ULA1_g8972__3377(.A (S[19]), .B (A[19]), .Z (ULA1_n_4298));
  NOR2_E ULA1_g8973__9719(.A (S[29]), .B (A[29]), .Z (ULA1_n_4299));
  NAND2_F ULA1_g8974__1591(.A (S[22]), .B (A[22]), .Z (ULA1_n_4300));
  NAND2_F ULA1_g8975__6789(.A (S[14]), .B (A[14]), .Z (ULA1_n_4301));
  NAND2_F ULA1_g8976__5927(.A (S[13]), .B (A[13]), .Z (ULA1_n_4302));
  NAND2_F ULA1_g8977__2001(.A (S[10]), .B (A[10]), .Z (ULA1_n_4304));
  NAND2_F ULA1_g8978__1122(.A (S[2]), .B (A[2]), .Z (ULA1_n_4305));
  NAND2_F ULA1_g8979__2005(.A (S[20]), .B (A[20]), .Z (ULA1_n_4306));
  NAND2_F ULA1_g8980__9771(.A (S[7]), .B (A[7]), .Z (ULA1_n_4307));
  NAND2_F ULA1_g8981__3457(.A (S[24]), .B (A[24]), .Z (ULA1_n_4308));
  NOR2_E ULA1_g8982__1279(.A (S[9]), .B (A[9]), .Z (ULA1_n_4309));
  NAND2_F ULA1_g8983__6179(.A (S[9]), .B (A[9]), .Z (ULA1_n_4310));
  NAND2_F ULA1_g8984__7837(.A (S[21]), .B (A[21]), .Z (ULA1_n_4311));
  AND2_I ULA1_g8985__7557(.A (ULA1_n_4365), .B (sel[1]), .Z
       (ULA1_n_4237));
  AND2_I ULA1_g8986__7654(.A (sel[1]), .B (sel[0]), .Z (ULA1_n_4252));
  INVERT_F ULA1_g8988(.A (A[21]), .Z (ULA1_n_4321));
  INVERT_F ULA1_g8989(.A (A[13]), .Z (ULA1_n_4323));
  INVERT_H ULA1_g8991(.A (A[30]), .Z (ULA1_n_4338));
  CLKI_I ULA1_g9003(.A (sel[0]), .Z (ULA1_n_4365));
  INVERT_F ULA1_g9004(.A (A[19]), .Z (ULA1_n_4384));
  INVERT_E ULA1_g9005(.A (A[9]), .Z (ULA1_n_4387));
  CLKI_I ULA1_g9020(.A (sel[1]), .Z (ULA1_n_4419));
  DFFR_E \registrador1_q_reg[30] (.RN (n_32), .CLK (clk), .D
       (S_ULA[30]), .Q (S[30]), .QBAR (UNCONNECTED));
  DFFR_E \registrador1_q_reg[21] (.RN (n_32), .CLK (clk), .D
       (S_ULA[21]), .Q (S[21]), .QBAR (UNCONNECTED0));
  DFFR_E \registrador1_q_reg[19] (.RN (n_32), .CLK (clk), .D
       (S_ULA[19]), .Q (S[19]), .QBAR (UNCONNECTED1));
  DFFR_E \registrador1_q_reg[13] (.RN (n_32), .CLK (clk), .D
       (S_ULA[13]), .Q (S[13]), .QBAR (UNCONNECTED2));
endmodule

